# Generated by Django 4.1.1 on 2022-10-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_approved_alter_album_creation_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='approved',
        ),
        migrations.AddField(
            model_name='album',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
