# Generated by Django 4.1.1 on 2022-10-14 07:33

import albums.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_remove_album_creation_datetime_album_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=80)),
                ('image', models.ImageField(upload_to='')),
                ('audio', models.FileField(upload_to='uploads/', validators=[albums.models.validate_file_extension])),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.album')),
            ],
        ),
    ]
